import streamlit as st

def show_content_disclaimer():
    """General AI content disclaimer (not pharma-specific)"""
    st.info("""
    💡 **AI-Generated Content Guidelines**

    This content is created by AI and should be used as a starting point.

    **Best Practices:**
    - ✓ Review and edit all AI-generated content
    - ✓ Verify facts, statistics, and claims
    - ✓ Ensure brand voice consistency
    - ✓ Check cultural appropriateness for target markets
    - ✓ Test with your audience before large-scale use

    **You are responsible for:**
    - Content accuracy
    - Brand representation
    - Compliance with platform policies
    - Legal/regulatory requirements for your industry
    """)

def show_first_time_disclaimer():
    """Show on first app load"""
    st.warning("""
    ⚠️ **Important: AI Content Disclaimer**

    All content generated by this platform is **draft content only**.

    **You must:**
    - Review all generated content before publishing
    - Verify accuracy of all claims and information
    - Ensure compliance with your industry regulations
    - Adapt content to your brand voice

    **We are not responsible for:**
    - Content published without review
    - Accuracy of AI-generated claims
    - Compliance with industry-specific regulations
    - Platform policy violations

    By using this platform, you agree to review all content before publication.
    """)

def add_draft_watermark(content: str) -> str:
    """Add draft watermark to content"""
    watermark = "\n\n---\n*⚠️ DRAFT CONTENT - Review before publishing*\n"
    return content + watermark
